name: Update_js

on:
  push:
   branches: 
      - main

  schedule:
     - cron: 50 2-14/4 * * * 

  release:
      types: [published]

  watch:
     types: started

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@main

      - name: update
        run: |
          wget https://raw.githubusercontent.com/firkerword/KPR/main/2.sh
          chmod 0755 ./2.sh
          ./2.sh

      - name: Push Commits
        run : |
          cd JD_Script
          git config --global user.email "136000981@qq.com"
          git config --global user.name "firkerword"
          export TZ='Asia/Shanghai'
          git add .
          git commit -m "github_actions" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: "main"
          
      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 3 
